### ISSUE TITLE
解决原生ViewPager当页数为2时的滑动Bug

### ISSUE THREAD

**Issue by JocelynChung0114** [xingda920813/LunboViewPager#1]
No work!!

**Comment by xingda920813** [comment]
现在的做法其实是比较 Tricky 的，页数正好为 2 时，会加倍为 4 页。

因为无限循环的存在，左右滑动时，看起来也是 2 页在交替切换。只是下方的指示器会变为 4 个。

若不加倍，页数为 2 时会有更严重的问题，即文档中说的“原生ViewPager当页数为2时的滑动Bug”。这个 Bug 的解决方式就是加倍了页数。

考虑到轮播图只有 2 页的情况比较罕见，所以 won't fix.
